Improve Vault environment validation in Jenkins pipeline
Added stricter error handling with `set -e` to ensure the script exits on failure. Introduced checks for `VAULT_ADDR` and `VAULT_TOKEN` environment variables, including logging and validation to prevent pipeline execution without a valid Vault token. Added a health check for the Vault server to ensure it is operational before proceeding.

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -30,6 +30,15 @@ pipeline {
                                 curl -v $VAULT_ADDR/v1/sys/health || true
                                 export TF_PLUGIN_CACHE_DIR=/var/jenkins_home/.terraform.d/plugin-cache
                                 mkdir -p $TF_PLUGIN_CACHE_DIR
+                                set -e
+                                echo "Checking Vault environment..."
+                                env | grep VAULT_ADDR
+                                if [ -z "$VAULT_TOKEN" ]; then
+                                echo "ERROR: VAULT_TOKEN is empty"
+                                exit 1
+                                fi
+                                echo "VAULT_TOKEN is present"
+                                curl -s $VAULT_ADDR/v1/sys/health
                                 rm -rf .terraform
                                 rm -rf .terraform.lock.hcl
                                 export VAULT_ADDR
